version: "3.9"

services:
  db:
    image: postgres:16
    container_name: dataroom-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataroom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dataroom"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
